### ISSUE TITLE
Every function that gets a property from PlayState doesn't work

### ISSUE THREAD

**Issue by BernardoGP4504** [PsychPorting/FNF-PsychEngine-Base-Mobile#138]
### Describe your bug here.

Title
Checking the code, it has to do with `MusicBeatState`'s `variables` map being null
And every function that needs to get something is trying to get it from that said map

![`setTextString: Object scoreTxt doesn't exist!`](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/101405920/1475713a-34ea-4063-aba9-1b48ab5c38a1)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

**Comment by mcagabe19** [comment]
I'm 100% sure it's fixed rn
