### ISSUE TITLE
Image not changin when modding files

### ISSUE THREAD

**Issue by Vini158916** [PsychPorting/FNF-PsychEngine-Base-Mobile#142]
### Describe your bug here.

I'm trying to change the icons of the charaters. But when i modify the icon it doesn't change in-game. Even modifying assets and even creating mods

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I only edited the icons images on assets game folder

**Comment by mcagabe19** [comment]
fixed ig, will include on next devbuild.
