### ISSUE TITLE
VideoSpriteHandler doesnt work

### ISSUE THREAD

**Issue by ryboy111** [PsychPorting/FNF-PsychEngine-Base-Mobile#143]
### Describe your bug here.

![Screenshot_20240612_072540](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/81989582/4c341061-822c-4004-b6ae-6aa596e3c73d)

Idk how to fix this I'm not very knowleged when it comes to haxeflixel

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by AStupidPersonXd123** [comment]
remove the script and that's it

**Comment by mcagabe19** [comment]
redownload psych from releases
