### ISSUE TITLE
Some images are completely black

### ISSUE THREAD

**Issue by GlitchVask** [PsychPorting/FNF-PsychEngine-Base-Mobile#144]
### Describe your bug here.

Some images with resolutions higher than 4096 are sometimes completely black.
![Screenshot_20240613-095458](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/5f504110-cc4e-4304-9e47-fbae4116c155)
![Screenshot_20240613-095458](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/5f504110-cc4e-4304-9e47-fbae4116c155)
![Screenshot_20240613-095427](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/0255c4dd-cb5b-4059-a8b0-ecd6a41dc547)
![Screenshot_20240613-095427](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/0255c4dd-cb5b-4059-a8b0-ecd6a41dc547)
![Screenshot_20240613-095307](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/f23c46cb-e4b8-435b-8719-9e325a52bc97)
![Screenshot_20240613-095307](https://github.com/PsychPorting/FNF-PsychEngine-Base-Mobile/assets/74579362/f23c46cb-e4b8-435b-8719-9e325a52bc97)

### Crash Log or logcat logs (if existing)

```bash
nothing
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
ram issue, get a better device
